language: node_js
node_js:
  - 12
jobs:
  include:
    - state: download doc
      if: type = cron
      script: npm run sync:all
      after_success: bash ./tools/updateDocsIfNeeded.sh
    - state: lint
      script: npm run lint
    - stage: deploy to staging
      if: (branch = master) AND type != cron
      script: npm run generate:staging
      deploy:
        provider: pages:git
        edge: true # opt in to dpl v2
        github_token: $GITHUB_TOKEN
        local_dir: dist
    - stage: deploy to production
      if: tag =~ /^release-/
      script: npm run generate:production
      deploy:
        provider: pages:git
        edge: true # opt in to dpl v2
        github_token: $GITHUB_TOKEN
        target_branch: production-pages
        local_dir: dist
        on:
          tags: true
      after_deploy:
        - sleep 30 # waiting for gh-pages build
        - git config --global user.name "Travis CI"
        - git config --global user.email "travis@example.org"
        - git config --global push.default simple
        - git clone --depth 1 --branch gh-pages https://$GITHUB_TOKEN@github.com/g0v/summit.g0v.tw
        - cd summit.g0v.tw
        - git submodule init
        - git submodule update --remote
        - git commit -a -m "Update submodule 2020"
        - git push -f
